package keyboard

var keyMap = map[KEY]string{
	// Letters
	A: "A", B: "B", C: "C", D: "D", E: "E", F: "F", G: "G", H: "H", I: "I", J: "J", K: "K", L: "L", M: "M",
	N: "N", O: "O", P: "P", Q: "Q", R: "R", S: "S", T: "T", U: "U", V: "V", W: "W", X: "X", Y: "Y", Z: "Z",

	// Numbers & Numpad
	N_0: "0", N_1: "1", N_2: "2", N_3: "3", N_4: "4", N_5: "5", N_6: "6", N_7: "7", N_8: "8", N_9: "9",
	NUM_0: "NUM_0", NUM_1: "NUM_1", NUM_2: "NUM_2", NUM_3: "NUM_3", NUM_4: "NUM_4",
	NUM_5: "NUM_5", NUM_6: "NUM_6", NUM_7: "NUM_7", NUM_8: "NUM_8", NUM_9: "NUM_9",
	NUM_MUL: "NUM_MUL", NUM_ADD: "NUM_ADD", NUM_SUB: "NUM_SUB", NUM_DEC: "NUM_DEC", NUM_DIV: "NUM_DIV",

	// F Keys
	F1: "F1", F2: "F2", F3: "F3", F4: "F4", F5: "F5", F6: "F6", F7: "F7", F8: "F8", F9: "F9", F10: "F10", F11: "F11", F12: "F12",

	// Control & System
	BACKSPACE: "BACKSPACE", TAB: "TAB", ENTER: "ENTER", SHIFT: "SHIFT", CTRL: "CTRL", ALT: "ALT",
	PAUSE: "PAUSE", CAPS_LOCK: "CAPS_LOCK", ESCAPE: "ESCAPE", SPACE: "SPACE",
	PAGE_UP: "PAGE_UP", PAGE_DOWN: "PAGE_DOWN", END: "END", HOME: "HOME",
	ARROW_LEFT: "LEFT", ARROW_UP: "UP", ARROW_RIGHT: "RIGHT", ARROW_DOWN: "DOWN",
	PRINT_SCREEN: "PRTSC", INSERT: "INSERT", DELETE: "DELETE", WIN: "WIN", RIGHT_WIN: "RWIN",
	NUM_LOCK: "NUM_LOCK", SCROLL_LOCK: "SCROLL_LOCK",
	LEFT_SHIFT: "L_SHIFT", RIGHT_SHIFT: "R_SHIFT", LEFT_CTRL: "L_CTRL", RIGHT_CTRL: "R_CTRL",
	LEFT_ALT: "L_ALT", RIGHT_ALT: "R_ALT",

	// Brightness and Launch Keys
	BRIGHTNESS_UP: "BRIGHT_UP", BRIGHTNESS_DOWN: "BRIGHT_DOWN",
	BROWSER_BACK: "BROWSER_BACK", BROWSER_FORWARD: "BROWSER_FORWARD", BROWSER_REFRESH: "BROWSER_REFRESH",
	BROWSER_STOP: "BROWSER_STOP", BROWSER_SEARCH: "BROWSER_SEARCH", BROWSER_FAVORITES: "BROWSER_FAVORITES", BROWSER_HOME: "BROWSER_HOME",
	LAUNCH_MAIL: "LAUNCH_MAIL", LAUNCH_MEDIA_SELECT: "LAUNCH_MEDIA", LAUNCH_APP1: "LAUNCH_APP1", LAUNCH_APP2: "LAUNCH_APP2",

	// OEM (Punctuation)
	OEM_1: ";", OEM_PLUS: "=", OEM_COMMA: ",", OEM_MINUS: "-", OEM_PERIOD: ".",
	OEM_2: "/", OEM_3: "`", OEM_4: "[", OEM_5: "\\", OEM_6: "]", OEM_7: "'",

	// Media
	VOLUME_MUTE: "VOL_MUTE", VOLUME_DOWN: "VOL_DOWN", VOLUME_UP: "VOL_UP",
	MEDIA_NEXT: "MEDIA_NEXT", MEDIA_PREV: "MEDIA_PREV", MEDIA_STOP: "MEDIA_STOP", MEDIA_PLAY: "MEDIA_PLAY",

	// Additional Keys
	CONTEXT_MENU: "CONTEXT_MENU", SLEEP: "SLEEP", SELECT: "SELECT", EXECUTE: "EXECUTE", HELP: "HELP",
}
