package mice

type ACTION string

const (
	CLICK_DOWN   ACTION = "CLICK_DOWN"
	CLICK_UP     ACTION = "CLICK_UP"
	SCROLL_UP    ACTION = "SCROLL_UP"
	SCROLL_DOWN  ACTION = "SCROLL_DOWN"
	SCROLL_LEFT  ACTION = "SCROLL_LEFT"
	SCROLL_RIGHT ACTION = "SCROLL_RIGHT"
)

type BUTTON string

const (
	LEFT_BUTTON    BUTTON = "LEFT"
	RIGHT_BUTTON   BUTTON = "RIGHT"
	MIDDLE_BUTTON  BUTTON = "MIDDLE"
	V_WHEEL        BUTTON = "V_WHEEL"
	H_WHEEL        BUTTON = "H_WHEEL"
	BACK_BUTTON    BUTTON = "BACK"
	FORWARD_BUTTON BUTTON = "FORWARD"
)
